name: changerelease
description: Run changerelease
inputs:
  changelog:
    description: 'Path to your CHANGELOG'
    required: false
    default: 'CHANGELOG.md'
  tag_prefix:
    description: 'The prefix that is on SemVer tags (i.e. "v" or nothing "")'
    default: 'v'
  github_token:
    description: "A GitHub token that can create and modify releases"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - --changelog ${{ inputs.changelog }}
  env:
    CR_TAG_PREFIX: ${{ inputs.tag_prefix }}
    CR_NO_TAG_PREFIX: ${{ inputs.tag_prefix == '' }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
