name: changerelease
description: Run changerelease
inputs:
  changelog:
    description: 'Path to your CHANGELOG'
    required: false
    default: 'CHANGELOG.md'
  github_token:
    description: "A GitHub token that can create and modify releases"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - --changelog ${{ inputs.changelog }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
