name: changerelease
description: Automatically update your GitHub Releases from CHANGELOG.md
branding:
  icon: upload-cloud
  color: white
inputs:
  changelog:
    description: 'Path to your CHANGELOG'
    required: false
    default: 'CHANGELOG.md'
  tag_prefix:
    description: 'The prefix that is on SemVer tags (i.e. "v" or nothing "")'
    default: 'v'
  github_token:
    description: "A GitHub token that can create and modify releases"
    required: true
  limit:
    description: 'Limit syncing to the latest X versions'
    default: 5
  remote_changelog:
    description: 'Get the CHANGELOG using the GitHub API (does not require a cloned repo)'
    default: true
runs:
  using: composite
  steps:
    - run: pip3 install $GITHUB_ACTION_PATH
      shell: bash
    - run: changerelease sync
      shell: bash
      env:
        CR_CHANGELOG: ${{ inputs.changelog }}
        CR_TAG_PREFIX: ${{ inputs.tag_prefix }}
        CR_NO_TAG_PREFIX: ${{ inputs.tag_prefix == '' }}
        CR_LIMIT: ${{ inputs.limit }}
        CR_REMOTE_CHANGELOG: ${{ inputs.remote_changelog }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
